const stockMovementTypeLabels: Record<string, string> = {
  CUSTOMER_RETURN_IN: 'เข้า - รับคืนจากลูกค้า',
  GRADE_ADJUST_IN: 'เข้า - ปรับเกรด',
  GRADE_ADJUST_OUT: 'ออก - ปรับเกรด',
  GRADE_ADJUST_REVERSE_IN: 'เข้า - ย้อนคืนการปรับเกรด',
  GRADE_ADJUST_REVERSE_OUT: 'ออก - ย้อนคืนการปรับเกรด',
  PENDING_SALE_OUT: 'ออก - รอขาย',
  PRODUCTION_INPUT_OUT: 'ออก - เบิกเข้าผลิต',
  PRODUCTION_INPUT_RETURN_STOCK_IN: 'เข้า - คืนวัตถุดิบเข้าสต๊อก',
  PRODUCTION_INPUT_RETURN_WIP_OUT: 'ออก - คืนวัตถุดิบจาก WIP',
  PRODUCTION_INPUT_REVERSE_STOCK_IN: 'เข้า - ย้อนคืนวัตถุดิบเข้าสต๊อก',
  PRODUCTION_INPUT_REVERSE_WIP_OUT: 'ออก - ย้อนคืน WIP',
  PRODUCTION_LOSS: 'ออก - สูญเสียจากการผลิต',
  PRODUCTION_OUTPUT_IN: 'เข้า - ผลิตเสร็จเข้า FG',
  PRODUCTION_OUTPUT_RM_IN: 'เข้า - ผลิตเสร็จเข้า RM',
  PRODUCTION_OUTPUT_REVERSE_STOCK_OUT: 'ออก - ย้อนคืนผลผลิตจากสต๊อก',
  PRODUCTION_OUTPUT_REVERSE_WIP_IN: 'เข้า - ย้อนคืน WIP',
  PRODUCTION_OUTPUT_WIP_OUT: 'ออก - ตัด WIP จากการผลิต',
  SALE_OUT: 'ออก - ขาย',
  STATUS_CONVERT_IN: 'เข้า - แปลงสถานะ',
  STATUS_CONVERT_OUT: 'ออก - แปลงสถานะ',
  STATUS_CONVERT_REVERSAL_IN: 'เข้า - ย้อนคืนการแปลงสถานะ',
  STATUS_CONVERT_REVERSAL_OUT: 'ออก - ย้อนคืนการแปลงสถานะ',
  STOCK_COUNT_GAIN: 'เข้า - ปรับนับสต๊อกเพิ่ม',
  STOCK_COUNT_LOSS: 'ออก - ปรับนับสต๊อกลด',
  STOCK_COUNT_REVERSE_IN: 'เข้า - ย้อนคืนการปรับนับสต๊อก',
  STOCK_COUNT_REVERSE_OUT: 'ออก - ย้อนคืนการปรับนับสต๊อก',
  WIP_IN: 'เข้า - รับเข้า WIP',
  ขายออก: 'ออก - ขาย',
  รับซื้อเข้า: 'เข้า - รับซื้อ',
  'รับซื้อเข้า-แก้ไข': 'ออก - Reverse บิลรับซื้อก่อนแก้ไข',
  'รับซื้อเข้า-ยกเลิก': 'ออก - Reverse บิลรับซื้อที่ยกเลิก',
  'ยกเลิกขายคืนสต๊อก': 'เข้า - ยกเลิกขายคืนสต๊อก',
  'แก้ไขบิลขายคืนสต๊อก': 'เข้า - แก้ไขบิลขายคืนสต๊อก',
  'รับคืนจากใบส่งของ WTO': 'เข้า - รับคืนจากใบส่งของ WTO',
  'ของขาดจากรับคืน WTO': 'ออก - ของขาดจากรับคืน WTO',
  'โอนระหว่างสาขา-เข้า': 'เข้า - โอนระหว่างสาขา',
  'โอนระหว่างสาขา-ออก': 'ออก - โอนระหว่างสาขา',
}

export function stockMovementTypeLabel(value: string | null | undefined) {
  const key = String(value ?? '').trim()
  if (!key) return '-'
  return stockMovementTypeLabels[key] ?? key
}
