import { NextResponse } from 'next/server'
import { AuthContextError, authContextErrorResponse, getCurrentAuthContext, requirePermission } from '@/lib/server/auth-context'
import { prisma } from '@/lib/server/prisma'

export const runtime = 'nodejs'

export async function GET(request: Request) {
  try {
    const context = await getCurrentAuthContext()
    requirePermission(context, 'system.settings.manage')

    // 1. Create logs table
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS public.weight_ticket_notification_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        weight_ticket_id bigint NOT NULL REFERENCES public.weight_tickets(id) ON DELETE CASCADE,
        delivery_channel text NOT NULL DEFAULT 'line',
        target_id text,
        status text NOT NULL,
        pdf_storage_bucket text,
        pdf_storage_key text,
        pdf_url text,
        line_request_id text,
        custom_message text,
        error_message text,
        requested_by text,
        sent_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT weight_ticket_notification_logs_channel_check CHECK (delivery_channel IN ('line')),
        CONSTRAINT weight_ticket_notification_logs_status_check CHECK (status IN ('sent', 'failed'))
      );
    `)

    // 2. Create indexes
    await prisma.$executeRawUnsafe(`
      CREATE INDEX IF NOT EXISTS idx_weight_ticket_notification_logs_ticket
        ON public.weight_ticket_notification_logs (weight_ticket_id, created_at DESC);
    `)
    await prisma.$executeRawUnsafe(`
      CREATE INDEX IF NOT EXISTS idx_weight_ticket_notification_logs_status
        ON public.weight_ticket_notification_logs (status, created_at DESC);
    `)

    // 3. Create bucket in storage.buckets
    await prisma.$executeRawUnsafe(`
      INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
      VALUES ('weight-ticket-pdfs', 'weight-ticket-pdfs', true, 10485760, ARRAY['application/pdf'])
      ON CONFLICT (id) DO UPDATE
      SET public = EXCLUDED.public,
          file_size_limit = EXCLUDED.file_size_limit,
          allowed_mime_types = EXCLUDED.allowed_mime_types;
    `)

    return NextResponse.json({ ok: true, message: 'ฐานข้อมูลและ Storage Bucket ได้รับการอัปเกรดสำเร็จเรียบร้อยแล้ว!' })
  } catch (caught) {
    if (caught instanceof AuthContextError) return authContextErrorResponse(caught)
    return NextResponse.json({ ok: false, error: caught instanceof Error ? caught.message : 'เกิดข้อผิดพลาดในการตั้งค่าฐานข้อมูล' })
  }
}
