begin;

-- Standalone / near-standalone public UUID PKs

alter table public.equity
  add column id_new bigint generated by default as identity;
update public.equity
set id_new = default
where id_new is null;

alter table public.bill_swap_history
  add column id_new bigint generated by default as identity;
update public.bill_swap_history
set id_new = default
where id_new is null;

alter table public.bill_swap_history
  alter column bill_id type bigint using bill_id::bigint,
  alter column before_supplier_id type bigint using before_supplier_id::bigint,
  alter column after_supplier_id type bigint using after_supplier_id::bigint;

alter table public.user_profiles
  add column id_new bigint generated by default as identity;
update public.user_profiles
set id_new = default
where id_new is null;

-- App auth/permission core tables

alter table public.app_permissions
  add column id_new bigint generated by default as identity;
update public.app_permissions
set id_new = default
where id_new is null;

alter table public.app_roles
  add column id_new bigint generated by default as identity;
update public.app_roles
set id_new = default
where id_new is null;

alter table public.app_users
  add column id_new bigint generated by default as identity;
update public.app_users
set id_new = default
where id_new is null;

alter table public.app_activity_logs
  add column id_new bigint generated by default as identity,
  add column actor_app_user_id_new bigint;
update public.app_activity_logs
set id_new = default
where id_new is null;

alter table public.app_audit_logs
  add column id_new bigint generated by default as identity,
  add column actor_app_user_id_new bigint;
update public.app_audit_logs
set id_new = default
where id_new is null;

alter table public.app_auth_events
  add column id_new bigint generated by default as identity,
  add column actor_app_user_id_new bigint,
  add column target_app_user_id_new bigint;
update public.app_auth_events
set id_new = default
where id_new is null;

alter table public.audit_logs
  add column id_new bigint generated by default as identity;
update public.audit_logs
set id_new = default
where id_new is null;

alter table public.app_activity_logs disable trigger app_activity_logs_append_only;
alter table public.app_audit_logs disable trigger app_audit_logs_append_only;

alter table public.app_role_permissions
  add column role_id_new bigint,
  add column permission_id_new bigint;

alter table public.app_user_roles
  add column user_id_new bigint,
  add column role_id_new bigint;

alter table public.app_user_branch_access
  add column user_id_new bigint;

update public.app_role_permissions rp
set role_id_new = r.id_new,
    permission_id_new = p.id_new
from public.app_roles r,
     public.app_permissions p
where rp.role_id = r.id
  and rp.permission_id = p.id;

update public.app_user_roles ur
set user_id_new = u.id_new,
    role_id_new = r.id_new
from public.app_users u,
     public.app_roles r
where ur.user_id = u.id
  and ur.role_id = r.id;

update public.app_user_branch_access uba
set user_id_new = u.id_new
from public.app_users u
where uba.user_id = u.id;

update public.app_activity_logs l
set actor_app_user_id_new = u.id_new
from public.app_users u
where l.actor_app_user_id = u.id;

update public.app_audit_logs l
set actor_app_user_id_new = u.id_new
from public.app_users u
where l.actor_app_user_id = u.id;

update public.app_auth_events e
set actor_app_user_id_new = actor_u.id_new
from public.app_users actor_u
where e.actor_app_user_id = actor_u.id;

update public.app_auth_events e
set target_app_user_id_new = target_u.id_new
from public.app_users target_u
where e.target_app_user_id = target_u.id;

alter table public.app_role_permissions
  alter column role_id_new set not null,
  alter column permission_id_new set not null;

alter table public.app_user_roles
  alter column user_id_new set not null,
  alter column role_id_new set not null;

alter table public.app_user_branch_access
  alter column user_id_new set not null;

drop index if exists public.idx_app_users_legacy_user_id;
drop index if exists public.idx_app_roles_legacy_role_id;
drop index if exists public.idx_app_role_permissions_permission_id;
drop index if exists public.idx_app_user_roles_role_id;
drop index if exists public.idx_app_activity_logs_actor_app_user_id;
drop index if exists public.idx_app_audit_logs_actor_app_user_id;
drop index if exists public.idx_app_auth_events_actor_app_user_id;
drop index if exists public.idx_app_auth_events_target_app_user_id;

alter table public.equity
  drop constraint if exists equity_pkey;

alter table public.bill_swap_history
  drop constraint if exists bill_swap_history_pkey;

alter table public.user_profiles
  drop constraint if exists user_profiles_pkey;

alter table public.app_role_permissions
  drop constraint if exists app_role_permissions_pkey,
  drop constraint if exists app_role_permissions_role_id_fkey,
  drop constraint if exists app_role_permissions_permission_id_fkey;

alter table public.app_user_roles
  drop constraint if exists app_user_roles_pkey,
  drop constraint if exists app_user_roles_user_id_fkey,
  drop constraint if exists app_user_roles_role_id_fkey;

alter table public.app_user_branch_access
  drop constraint if exists app_user_branch_access_pkey,
  drop constraint if exists app_user_branch_access_user_id_fkey;

alter table public.app_activity_logs
  drop constraint if exists app_activity_logs_pkey,
  drop constraint if exists app_activity_logs_actor_app_user_id_fkey;

alter table public.app_audit_logs
  drop constraint if exists app_audit_logs_pkey,
  drop constraint if exists app_audit_logs_actor_app_user_id_fkey;

alter table public.app_auth_events
  drop constraint if exists app_auth_events_pkey,
  drop constraint if exists app_auth_events_actor_app_user_id_fkey,
  drop constraint if exists app_auth_events_target_app_user_id_fkey;

alter table public.app_users
  drop constraint if exists app_users_pkey;

alter table public.app_roles
  drop constraint if exists app_roles_pkey;

alter table public.app_permissions
  drop constraint if exists app_permissions_pkey;

alter table public.audit_logs
  drop constraint if exists audit_logs_pkey;

alter table public.equity
  drop column id;
alter table public.equity
  rename column id_new to id;
alter table public.equity
  add constraint equity_pkey primary key (id);

alter table public.bill_swap_history
  drop column id;
alter table public.bill_swap_history
  rename column id_new to id;
alter table public.bill_swap_history
  add constraint bill_swap_history_pkey primary key (id);

alter table public.user_profiles
  drop column id;
alter table public.user_profiles
  rename column id_new to id;
alter table public.user_profiles
  add constraint user_profiles_pkey primary key (id);

alter table public.app_permissions
  drop column id;
alter table public.app_permissions
  rename column id_new to id;
alter table public.app_permissions
  add constraint app_permissions_pkey primary key (id);

alter table public.app_roles
  drop column legacy_role_id,
  drop column id;
alter table public.app_roles
  rename column id_new to id;
alter table public.app_roles
  add constraint app_roles_pkey primary key (id);

alter table public.app_users
  drop column legacy_user_id,
  drop column legacy_profile_id,
  drop column id;
alter table public.app_users
  rename column id_new to id;
alter table public.app_users
  add constraint app_users_pkey primary key (id);

alter table public.app_role_permissions
  drop column role_id,
  drop column permission_id;
alter table public.app_role_permissions
  rename column role_id_new to role_id;
alter table public.app_role_permissions
  rename column permission_id_new to permission_id;
alter table public.app_role_permissions
  add constraint app_role_permissions_pkey primary key (role_id, permission_id),
  add constraint app_role_permissions_role_id_fkey foreign key (role_id) references public.app_roles(id) on delete cascade,
  add constraint app_role_permissions_permission_id_fkey foreign key (permission_id) references public.app_permissions(id) on delete cascade;

alter table public.app_user_roles
  drop column user_id,
  drop column role_id;
alter table public.app_user_roles
  rename column user_id_new to user_id;
alter table public.app_user_roles
  rename column role_id_new to role_id;
alter table public.app_user_roles
  add constraint app_user_roles_pkey primary key (user_id, role_id),
  add constraint app_user_roles_user_id_fkey foreign key (user_id) references public.app_users(id) on delete cascade,
  add constraint app_user_roles_role_id_fkey foreign key (role_id) references public.app_roles(id) on delete restrict;

alter table public.app_user_branch_access
  drop column user_id;
alter table public.app_user_branch_access
  rename column user_id_new to user_id;
alter table public.app_user_branch_access
  add constraint app_user_branch_access_pkey primary key (user_id, branch_id),
  add constraint app_user_branch_access_user_id_fkey foreign key (user_id) references public.app_users(id) on delete cascade;

alter table public.app_activity_logs
  drop column actor_app_user_id,
  drop column id;
alter table public.app_activity_logs
  rename column actor_app_user_id_new to actor_app_user_id;
alter table public.app_activity_logs
  rename column id_new to id;
alter table public.app_activity_logs
  add constraint app_activity_logs_pkey primary key (id),
  add constraint app_activity_logs_actor_app_user_id_fkey foreign key (actor_app_user_id) references public.app_users(id) on update no action;

alter table public.app_audit_logs
  drop column actor_app_user_id,
  drop column id;
alter table public.app_audit_logs
  rename column actor_app_user_id_new to actor_app_user_id;
alter table public.app_audit_logs
  rename column id_new to id;
alter table public.app_audit_logs
  add constraint app_audit_logs_pkey primary key (id),
  add constraint app_audit_logs_actor_app_user_id_fkey foreign key (actor_app_user_id) references public.app_users(id) on update no action;

alter table public.app_auth_events
  drop column actor_app_user_id,
  drop column target_app_user_id,
  drop column id;
alter table public.app_auth_events
  rename column actor_app_user_id_new to actor_app_user_id;
alter table public.app_auth_events
  rename column target_app_user_id_new to target_app_user_id;
alter table public.app_auth_events
  rename column id_new to id;
alter table public.app_auth_events
  add constraint app_auth_events_pkey primary key (id),
  add constraint app_auth_events_actor_app_user_id_fkey foreign key (actor_app_user_id) references public.app_users(id) on delete set null,
  add constraint app_auth_events_target_app_user_id_fkey foreign key (target_app_user_id) references public.app_users(id) on delete set null;

alter table public.audit_logs
  drop column id;
alter table public.audit_logs
  rename column id_new to id;
alter table public.audit_logs
  add constraint audit_logs_pkey primary key (id);

create index if not exists idx_app_role_permissions_permission_id
  on public.app_role_permissions(permission_id);
create index if not exists idx_app_user_roles_role_id
  on public.app_user_roles(role_id);
create index if not exists idx_app_activity_logs_actor_app_user_id
  on public.app_activity_logs(actor_app_user_id);
create index if not exists idx_app_audit_logs_actor_app_user_id
  on public.app_audit_logs(actor_app_user_id);
create index if not exists idx_app_auth_events_actor_app_user_id
  on public.app_auth_events(actor_app_user_id);
create index if not exists idx_app_auth_events_target_app_user_id
  on public.app_auth_events(target_app_user_id);

alter table public.app_activity_logs enable trigger app_activity_logs_append_only;
alter table public.app_audit_logs enable trigger app_audit_logs_append_only;

commit;
