create table if not exists public.account_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  account_group text not null,
  requires_counterparty boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_account_categories_active_sort
  on public.account_categories (active, sort_order);

insert into public.account_categories (code, name, account_group, requires_counterparty, sort_order)
values
  ('cash', 'เงินสด', 'cash', false, 10),
  ('bank', 'บัญชีธนาคาร', 'bank', false, 20),
  ('virtual', 'บัญชีเจ้าหนี้เงินทดรองจ่าย', 'virtual', true, 30)
on conflict (code) do update
set name = excluded.name,
    account_group = excluded.account_group,
    requires_counterparty = excluded.requires_counterparty,
    sort_order = excluded.sort_order,
    updated_at = now();

alter table public.accounts
  drop constraint if exists accounts_account_group_fkey;

alter table public.accounts
  add constraint accounts_account_group_fkey
  foreign key (account_group) references public.account_categories(code);
