alter table public.bank_names
  add column if not exists id_new bigint generated by default as identity;

alter table public.bank_names
  drop constraint if exists bank_names_pkey;

alter table public.bank_names
  drop column if exists id;

alter table public.bank_names
  rename column id_new to id;

alter table public.bank_names
  add constraint bank_names_pkey primary key (id);

alter table public.payment_methods
  add column if not exists id_new bigint generated by default as identity;

alter table public.payment_methods
  drop constraint if exists payment_methods_pkey;

alter table public.payment_methods
  drop column if exists id;

alter table public.payment_methods
  rename column id_new to id;

alter table public.payment_methods
  add constraint payment_methods_pkey primary key (id);

alter table public.product_units
  add column if not exists id_new bigint generated by default as identity;

alter table public.product_units
  drop constraint if exists product_units_pkey;

alter table public.product_units
  drop column if exists id;

alter table public.product_units
  rename column id_new to id;

alter table public.product_units
  add constraint product_units_pkey primary key (id);

alter table public.product_types
  add column if not exists id_new bigint generated by default as identity;

alter table public.product_types
  drop constraint if exists product_types_pkey;

alter table public.product_types
  drop column if exists id;

alter table public.product_types
  rename column id_new to id;

alter table public.product_types
  add constraint product_types_pkey primary key (id);
