alter table public.expenses
  drop constraint if exists expenses_category_id_fkey;

alter table public.expense_types
  add column if not exists id_new bigint generated by default as identity;

alter table public.expense_categories
  add column if not exists id_new bigint generated by default as identity;

alter table public.expenses
  add column if not exists category_id_new bigint;

update public.expenses as e
set category_id_new = c.id_new
from public.expense_categories as c
where e.category_id = c.id;

alter table public.expense_types
  drop constraint if exists expense_types_pkey;

alter table public.expense_types
  rename column id to legacy_id;

alter table public.expense_types
  rename column id_new to id;

alter table public.expense_types
  add constraint expense_types_pkey primary key (id);

create unique index if not exists expense_types_legacy_id_key
  on public.expense_types (legacy_id);

alter table public.expense_categories
  drop constraint if exists expense_categories_pkey;

alter table public.expense_categories
  rename column id to legacy_id;

alter table public.expense_categories
  rename column id_new to id;

alter table public.expense_categories
  add constraint expense_categories_pkey primary key (id);

create unique index if not exists expense_categories_legacy_id_key
  on public.expense_categories (legacy_id);

alter table public.expense_categories
  drop column if exists expense_type_id;

alter table public.expense_categories
  add column expense_type_id bigint;

alter table public.expense_categories
  add constraint expense_categories_expense_type_id_fkey
  foreign key (expense_type_id) references public.expense_types (id)
  on delete no action
  on update no action;

alter table public.expenses
  rename column category_id to category_legacy_id;

alter table public.expenses
  rename column category_id_new to category_id;

alter table public.expenses
  add constraint expenses_category_id_fkey
  foreign key (category_id) references public.expense_categories (id)
  on delete no action
  on update no action;
