create table public.purchase_bill_status_logs (
  event_key text not null,
  action text not null,
  from_status text null,
  to_status text not null,
  purchase_bill_doc_no text not null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  purchase_bill_id bigint not null references public.purchase_bills(id) on delete cascade
);

create unique index idx_purchase_bill_status_logs_event_key
  on public.purchase_bill_status_logs(event_key);

create index idx_purchase_bill_status_logs_bill_created
  on public.purchase_bill_status_logs(purchase_bill_id, created_at desc);

with event_rows as (
  select
    pb.id as purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    coalesce(pb.created_at, pb.updated_at, now()) as created_at,
    pb.created_by,
    'created'::text as action,
    null::text as from_status,
    'unpaid'::text as to_status,
    null::text as note,
    jsonb_build_object('source', 'migration_backfill') as meta,
    0 as sort_order,
    null::bigint as related_id
  from public.purchase_bills pb

  union all

  select
    pb.id as purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    coalesce(p.created_at, pb.created_at, now()) as created_at,
    p.created_by,
    'payment_recorded'::text as action,
    null::text as from_status,
    case
      when coalesce(pb.payable_balance, 0) <= 0.01 then 'paid'
      else 'partial'
    end::text as to_status,
    p.notes as note,
    jsonb_build_object(
      'paymentDocNo', p.doc_no,
      'voucherId', p.voucher_id,
      'amount', coalesce(p.amount, 0),
      'withholdingTax', coalesce(p.withholding_tax, 0),
      'discount', coalesce(p.discount, 0),
      'fee', coalesce(p.fee, p.bank_fee, 0),
      'method', p.method
    ) as meta,
    1 as sort_order,
    p.id as related_id
  from public.payments p
  join public.purchase_bills pb on pb.id = p.bill_id
  where coalesce(p.status, 'active') <> 'cancelled'

  union all

  select
    pb.id as purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    coalesce(pb.cancelled_at, pb.updated_at, now()) as created_at,
    pb.cancelled_by as created_by,
    'cancelled'::text as action,
    null::text as from_status,
    'cancelled'::text as to_status,
    pb.cancel_note as note,
    jsonb_build_object('source', 'migration_backfill') as meta,
    2 as sort_order,
    null::bigint as related_id
  from public.purchase_bills pb
  where pb.cancelled_at is not null or lower(coalesce(pb.status, '')) = 'cancelled'
),
ordered_events as (
  select
    *,
    row_number() over (
      partition by purchase_bill_id
      order by created_at, sort_order, related_id nulls first
    ) as seq
  from event_rows
)
insert into public.purchase_bill_status_logs (
  event_key,
  action,
  from_status,
  to_status,
  purchase_bill_doc_no,
  note,
  meta,
  created_at,
  created_by,
  purchase_bill_id
)
select
  'PBLOG-' || purchase_bill_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  from_status,
  to_status,
  purchase_bill_doc_no,
  note,
  meta,
  created_at,
  created_by,
  purchase_bill_id
from ordered_events;
