begin;

create table if not exists public.godown_kpi_evaluations (
  id bigint generated by default as identity primary key,
  eval_date date not null,
  godown_id bigint not null references public.godowns(id),
  godown_code text not null,
  godown_name text not null,
  accuracy integer not null default 3,
  speed integer not null default 3,
  target_hit integer not null default 3,
  avg_score numeric(2,1) not null,
  problems text default '',
  solutions text default '',
  evaluated_by text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint godown_kpi_evaluations_score_check check (accuracy between 1 and 5 and speed between 1 and 5 and target_hit between 1 and 5),
  constraint godown_kpi_evaluations_date_godown_key unique (eval_date, godown_id)
);

create index if not exists godown_kpi_evaluations_godown_id_idx on public.godown_kpi_evaluations(godown_id);

insert into public.godown_kpi_evaluations (
  eval_date, godown_id, godown_code, godown_name, accuracy, speed, target_hit,
  avg_score, problems, solutions, evaluated_by, created_at, updated_at
)
select e.eval_date, g.id, g.code, g.name, e.accuracy, e.speed, e.target_hit,
       e.avg_score, e.problems, e.solutions, e.evaluated_by, e.created_at, e.updated_at
from public.warehouse_kpi_evaluations e
join public.warehouses w on w.id = e.warehouse_id
join public.godowns g on g.code = w.code
on conflict (eval_date, godown_id) do update set
  godown_code = excluded.godown_code,
  godown_name = excluded.godown_name,
  accuracy = excluded.accuracy,
  speed = excluded.speed,
  target_hit = excluded.target_hit,
  avg_score = excluded.avg_score,
  problems = excluded.problems,
  solutions = excluded.solutions,
  evaluated_by = excluded.evaluated_by,
  updated_at = excluded.updated_at;

comment on table public.godown_kpi_evaluations is 'KPI evaluations for physical godowns; separate from stock warehouse KPI history.';

commit;
