create table if not exists public.production_output_drafts (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.production_orders(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text null,
  updated_by text null
);

create index if not exists idx_production_output_drafts_updated_at
  on public.production_output_drafts(updated_at);

comment on table public.production_output_drafts is
  'Unposted production output form drafts. Drafts do not affect WIP, stock, or stock ledger until production output is posted.';
