begin;

create or replace function public.__wave1_drop_fk_constraints(p_table text, p_column text)
returns void
language plpgsql
as $$
declare
  r record;
begin
  for r in
    select tc.constraint_name
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
    where tc.table_schema = 'public'
      and tc.table_name = p_table
      and tc.constraint_type = 'FOREIGN KEY'
      and kcu.column_name = p_column
  loop
    execute format('alter table public.%I drop constraint %I', p_table, r.constraint_name);
  end loop;
end;
$$;

create or replace function public.__wave1_assert_backfill(p_table text, p_old_column text, p_new_column text)
returns void
language plpgsql
as $$
declare
  missing_count bigint;
begin
  execute format(
    'select count(*) from public.%I where %I is not null and %I is null',
    p_table,
    p_old_column,
    p_new_column
  )
  into missing_count;

  if missing_count > 0 then
    raise exception 'Wave 1 backfill failed for %.% -> % (% rows)', p_table, p_old_column, p_new_column, missing_count;
  end if;
end;
$$;

-- Foundation masters: add bigint ids first while legacy text ids are still the live PK/FK surface.
alter table public.branches add column id_new bigint generated by default as identity;
alter table public.warehouses add column id_new bigint generated by default as identity;
alter table public.customers add column id_new bigint generated by default as identity;
alter table public.salespersons add column id_new bigint generated by default as identity;
alter table public.suppliers add column id_new bigint generated by default as identity;

-- Add new bigint ref columns for Wave 1.
alter table public.accounts add column branch_id_new bigint;
alter table public.app_user_branch_access add column branch_id_new bigint;
alter table public.assets add column branch_id_new bigint;
alter table public.assets add column supplier_id_new bigint;
alter table public.customers add column sales_id_new bigint;
alter table public.expenses add column branch_id_new bigint;
alter table public.grade_adjustments add column warehouse_id_new bigint;
alter table public.payments add column supplier_id_new bigint;
alter table public.payments add column branch_id_new bigint;
alter table public.po_buys add column supplier_id_new bigint;
alter table public.po_buys add column branch_id_new bigint;
alter table public.po_buys add column warehouse_id_new bigint;
alter table public.po_sells add column customer_id_new bigint;
alter table public.po_sells add column branch_id_new bigint;
alter table public.po_sells add column warehouse_id_new bigint;
alter table public.production_lines add column branch_id_new bigint;
alter table public.production_machines add column branch_id_new bigint;
alter table public.production_orders add column branch_id_new bigint;
alter table public.production_orders add column warehouse_id_new bigint;
alter table public.production_orders add column warehouse_from_id_new bigint;
alter table public.production_orders add column warehouse_wip_id_new bigint;
alter table public.production_orders add column warehouse_to_id_new bigint;
alter table public.production_orders add column warehouse_return_id_new bigint;
alter table public.purchase_bills add column supplier_id_new bigint;
alter table public.purchase_bills add column branch_id_new bigint;
alter table public.purchase_bills add column warehouse_id_new bigint;
alter table public.purchase_bills add column sales_id_new bigint;
alter table public.receipts add column customer_id_new bigint;
alter table public.receipts add column branch_id_new bigint;
alter table public.sales_bills add column customer_id_new bigint;
alter table public.sales_bills add column branch_id_new bigint;
alter table public.sales_bills add column warehouse_id_new bigint;
alter table public.sales_bills add column sales_id_new bigint;
alter table public.stock_adjustments add column branch_id_new bigint;
alter table public.stock_adjustments add column warehouse_id_new bigint;
alter table public.stock_issues add column customer_id_new bigint;
alter table public.stock_issues add column branch_id_new bigint;
alter table public.stock_issues add column warehouse_id_new bigint;
alter table public.stock_ledger add column warehouse_id_new bigint;
alter table public.stock_ledger add column branch_id_new bigint;
alter table public.supplier_advance_payments add column branch_id_new bigint;
alter table public.supplier_advance_payments add column supplier_id_new bigint;
alter table public.supplier_bank_accounts add column supplier_id_new bigint;
alter table public.suppliers add column branch_id_new bigint;
alter table public.suppliers add column sales_id_new bigint;
alter table public.trading_deals add column supplier_id_new bigint;
alter table public.trading_deals add column customer_id_new bigint;
alter table public.users add column branch_id_new bigint;
alter table public.warehouses add column branch_id_new bigint;
alter table public.weight_tickets add column branch_id_new bigint;
alter table public.weight_tickets add column supplier_id_new bigint;
alter table public.weight_tickets add column customer_id_new bigint;

-- Backfill master-linked bigint refs.
update public.accounts t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.app_user_branch_access t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.assets t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.assets t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.customers t set sales_id_new = sp.id_new from public.salespersons sp where t.sales_id = sp.id;
update public.expenses t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.grade_adjustments t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.payments t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.payments t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.po_buys t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.po_buys t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.po_buys t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.po_sells t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;
update public.po_sells t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.po_sells t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.production_lines t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.production_machines t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.production_orders t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.production_orders t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.production_orders t set warehouse_from_id_new = w.id_new from public.warehouses w where t.warehouse_from_id = w.id;
update public.production_orders t set warehouse_wip_id_new = w.id_new from public.warehouses w where t.warehouse_wip_id = w.id;
update public.production_orders t set warehouse_to_id_new = w.id_new from public.warehouses w where t.warehouse_to_id = w.id;
update public.production_orders t set warehouse_return_id_new = w.id_new from public.warehouses w where t.warehouse_return_id = w.id;
update public.purchase_bills t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.purchase_bills t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.purchase_bills t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.purchase_bills t set sales_id_new = sp.id_new from public.salespersons sp where t.sales_id = sp.id;
update public.receipts t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;
update public.receipts t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.sales_bills t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;
update public.sales_bills t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.sales_bills t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.sales_bills t set sales_id_new = sp.id_new from public.salespersons sp where t.sales_id = sp.id;
update public.stock_adjustments t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.stock_adjustments t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.stock_issues t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;
update public.stock_issues t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.stock_issues t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.stock_ledger t set warehouse_id_new = w.id_new from public.warehouses w where t.warehouse_id = w.id;
update public.stock_ledger t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.supplier_advance_payments t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.supplier_advance_payments t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.supplier_bank_accounts t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.suppliers t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.suppliers t set sales_id_new = sp.id_new from public.salespersons sp where t.sales_id = sp.id;
update public.trading_deals t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.trading_deals t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;
update public.users t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.warehouses t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.weight_tickets t set branch_id_new = b.id_new from public.branches b where t.branch_id = b.id;
update public.weight_tickets t set supplier_id_new = s.id_new from public.suppliers s where t.supplier_id = s.id;
update public.weight_tickets t set customer_id_new = c.id_new from public.customers c where t.customer_id = c.id;

-- Abort if any non-null legacy ref failed to map.
select public.__wave1_assert_backfill('accounts', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('app_user_branch_access', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('assets', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('assets', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('customers', 'sales_id', 'sales_id_new');
select public.__wave1_assert_backfill('expenses', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('grade_adjustments', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('payments', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('payments', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('po_buys', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('po_buys', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('po_buys', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('po_sells', 'customer_id', 'customer_id_new');
select public.__wave1_assert_backfill('po_sells', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('po_sells', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('production_lines', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('production_machines', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('production_orders', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('production_orders', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('production_orders', 'warehouse_from_id', 'warehouse_from_id_new');
select public.__wave1_assert_backfill('production_orders', 'warehouse_wip_id', 'warehouse_wip_id_new');
select public.__wave1_assert_backfill('production_orders', 'warehouse_to_id', 'warehouse_to_id_new');
select public.__wave1_assert_backfill('production_orders', 'warehouse_return_id', 'warehouse_return_id_new');
select public.__wave1_assert_backfill('purchase_bills', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('purchase_bills', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('purchase_bills', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('purchase_bills', 'sales_id', 'sales_id_new');
select public.__wave1_assert_backfill('receipts', 'customer_id', 'customer_id_new');
select public.__wave1_assert_backfill('receipts', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('sales_bills', 'customer_id', 'customer_id_new');
select public.__wave1_assert_backfill('sales_bills', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('sales_bills', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('sales_bills', 'sales_id', 'sales_id_new');
select public.__wave1_assert_backfill('stock_adjustments', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('stock_adjustments', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('stock_issues', 'customer_id', 'customer_id_new');
select public.__wave1_assert_backfill('stock_issues', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('stock_issues', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('stock_ledger', 'warehouse_id', 'warehouse_id_new');
select public.__wave1_assert_backfill('stock_ledger', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('supplier_advance_payments', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('supplier_advance_payments', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('supplier_bank_accounts', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('suppliers', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('suppliers', 'sales_id', 'sales_id_new');
select public.__wave1_assert_backfill('trading_deals', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('trading_deals', 'customer_id', 'customer_id_new');
select public.__wave1_assert_backfill('users', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('warehouses', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('weight_tickets', 'branch_id', 'branch_id_new');
select public.__wave1_assert_backfill('weight_tickets', 'supplier_id', 'supplier_id_new');
select public.__wave1_assert_backfill('weight_tickets', 'customer_id', 'customer_id_new');

-- Drop FKs on legacy text refs before swapping columns.
select public.__wave1_drop_fk_constraints('accounts', 'branch_id');
select public.__wave1_drop_fk_constraints('app_user_branch_access', 'branch_id');
select public.__wave1_drop_fk_constraints('assets', 'branch_id');
select public.__wave1_drop_fk_constraints('assets', 'supplier_id');
select public.__wave1_drop_fk_constraints('expenses', 'branch_id');
select public.__wave1_drop_fk_constraints('grade_adjustments', 'warehouse_id');
select public.__wave1_drop_fk_constraints('payments', 'supplier_id');
select public.__wave1_drop_fk_constraints('payments', 'branch_id');
select public.__wave1_drop_fk_constraints('po_buys', 'supplier_id');
select public.__wave1_drop_fk_constraints('po_sells', 'customer_id');
select public.__wave1_drop_fk_constraints('production_lines', 'branch_id');
select public.__wave1_drop_fk_constraints('production_machines', 'branch_id');
select public.__wave1_drop_fk_constraints('production_orders', 'branch_id');
select public.__wave1_drop_fk_constraints('production_orders', 'warehouse_id');
select public.__wave1_drop_fk_constraints('purchase_bills', 'supplier_id');
select public.__wave1_drop_fk_constraints('purchase_bills', 'branch_id');
select public.__wave1_drop_fk_constraints('purchase_bills', 'warehouse_id');
select public.__wave1_drop_fk_constraints('receipts', 'customer_id');
select public.__wave1_drop_fk_constraints('receipts', 'branch_id');
select public.__wave1_drop_fk_constraints('sales_bills', 'customer_id');
select public.__wave1_drop_fk_constraints('sales_bills', 'branch_id');
select public.__wave1_drop_fk_constraints('sales_bills', 'warehouse_id');
select public.__wave1_drop_fk_constraints('stock_issues', 'customer_id');
select public.__wave1_drop_fk_constraints('stock_issues', 'branch_id');
select public.__wave1_drop_fk_constraints('stock_issues', 'warehouse_id');
select public.__wave1_drop_fk_constraints('stock_ledger', 'branch_id');
select public.__wave1_drop_fk_constraints('stock_ledger', 'warehouse_id');
select public.__wave1_drop_fk_constraints('supplier_advance_payments', 'branch_id');
select public.__wave1_drop_fk_constraints('supplier_advance_payments', 'supplier_id');
select public.__wave1_drop_fk_constraints('supplier_bank_accounts', 'supplier_id');
select public.__wave1_drop_fk_constraints('suppliers', 'branch_id');
select public.__wave1_drop_fk_constraints('trading_deals', 'customer_id');
select public.__wave1_drop_fk_constraints('trading_deals', 'supplier_id');
select public.__wave1_drop_fk_constraints('warehouses', 'branch_id');
select public.__wave1_drop_fk_constraints('weight_tickets', 'branch_id');
select public.__wave1_drop_fk_constraints('weight_tickets', 'customer_id');
select public.__wave1_drop_fk_constraints('weight_tickets', 'supplier_id');

-- Drop indexes / composite constraints that would otherwise remain on legacy text columns.
alter table public.app_user_branch_access drop constraint app_user_branch_access_pkey;
drop index if exists public.idx_app_user_branch_access_branch_id;
drop index if exists public.idx_pmt_supplier;
drop index if exists public.production_lines_branch_id_idx;
drop index if exists public.production_machines_branch_id_idx;
drop index if exists public.idx_pb_branch;
drop index if exists public.idx_pb_supplier;
drop index if exists public.idx_sb_branch;
drop index if exists public.idx_sb_customer;
drop index if exists public.idx_stock_adjustments_branch;
drop index if exists public.stock_ledger_opening_unique;
drop index if exists public.idx_supplier_advance_payments_branch;
drop index if exists public.idx_supplier_advance_payments_supplier;
drop index if exists public.uq_supplier_bank_accounts_supplier_account;
drop index if exists public.idx_supplier_bank_accounts_supplier;
drop index if exists public.idx_suppliers_branch;
drop index if exists public.idx_weight_tickets_branch;
drop index if exists public.idx_weight_tickets_customer;
drop index if exists public.idx_weight_tickets_supplier;

-- Swap master PKs: keep old text ids as legacy_id and promote bigint ids to live PK.
alter table public.branches drop constraint branches_pkey;
alter table public.branches rename column id to legacy_id;
alter table public.branches rename column id_new to id;
alter table public.branches add constraint branches_pkey primary key (id);
alter table public.branches add constraint branches_legacy_id_key unique (legacy_id);

alter table public.warehouses drop constraint warehouses_pkey;
alter table public.warehouses rename column id to legacy_id;
alter table public.warehouses rename column id_new to id;
alter table public.warehouses add constraint warehouses_pkey primary key (id);
alter table public.warehouses add constraint warehouses_legacy_id_key unique (legacy_id);

alter table public.customers drop constraint customers_pkey;
alter table public.customers rename column id to legacy_id;
alter table public.customers rename column id_new to id;
alter table public.customers add constraint customers_pkey primary key (id);
alter table public.customers add constraint customers_legacy_id_key unique (legacy_id);

alter table public.salespersons drop constraint salespersons_pkey;
alter table public.salespersons rename column id to legacy_id;
alter table public.salespersons rename column id_new to id;
alter table public.salespersons add constraint salespersons_pkey primary key (id);
alter table public.salespersons add constraint salespersons_legacy_id_key unique (legacy_id);

alter table public.suppliers drop constraint suppliers_pkey;
alter table public.suppliers rename column id to legacy_id;
alter table public.suppliers rename column id_new to id;
alter table public.suppliers add constraint suppliers_pkey primary key (id);
alter table public.suppliers add constraint suppliers_legacy_id_key unique (legacy_id);

-- Swap ref columns so the canonical column names become bigint.
alter table public.accounts rename column branch_id to branch_legacy_id;
alter table public.accounts rename column branch_id_new to branch_id;

alter table public.app_user_branch_access rename column branch_id to branch_legacy_id;
alter table public.app_user_branch_access rename column branch_id_new to branch_id;

alter table public.assets rename column branch_id to branch_legacy_id;
alter table public.assets rename column branch_id_new to branch_id;
alter table public.assets rename column supplier_id to supplier_legacy_id;
alter table public.assets rename column supplier_id_new to supplier_id;

alter table public.customers rename column sales_id to sales_legacy_id;
alter table public.customers rename column sales_id_new to sales_id;

alter table public.expenses rename column branch_id to branch_legacy_id;
alter table public.expenses rename column branch_id_new to branch_id;

alter table public.grade_adjustments rename column warehouse_id to warehouse_legacy_id;
alter table public.grade_adjustments rename column warehouse_id_new to warehouse_id;

alter table public.payments rename column supplier_id to supplier_legacy_id;
alter table public.payments rename column supplier_id_new to supplier_id;
alter table public.payments rename column branch_id to branch_legacy_id;
alter table public.payments rename column branch_id_new to branch_id;

alter table public.po_buys rename column supplier_id to supplier_legacy_id;
alter table public.po_buys rename column supplier_id_new to supplier_id;
alter table public.po_buys rename column branch_id to branch_legacy_id;
alter table public.po_buys rename column branch_id_new to branch_id;
alter table public.po_buys rename column warehouse_id to warehouse_legacy_id;
alter table public.po_buys rename column warehouse_id_new to warehouse_id;

alter table public.po_sells rename column customer_id to customer_legacy_id;
alter table public.po_sells rename column customer_id_new to customer_id;
alter table public.po_sells rename column branch_id to branch_legacy_id;
alter table public.po_sells rename column branch_id_new to branch_id;
alter table public.po_sells rename column warehouse_id to warehouse_legacy_id;
alter table public.po_sells rename column warehouse_id_new to warehouse_id;

alter table public.production_lines rename column branch_id to branch_legacy_id;
alter table public.production_lines rename column branch_id_new to branch_id;

alter table public.production_machines rename column branch_id to branch_legacy_id;
alter table public.production_machines rename column branch_id_new to branch_id;

alter table public.production_orders rename column branch_id to branch_legacy_id;
alter table public.production_orders rename column branch_id_new to branch_id;
alter table public.production_orders rename column warehouse_id to warehouse_legacy_id;
alter table public.production_orders rename column warehouse_id_new to warehouse_id;
alter table public.production_orders rename column warehouse_from_id to warehouse_from_legacy_id;
alter table public.production_orders rename column warehouse_from_id_new to warehouse_from_id;
alter table public.production_orders rename column warehouse_wip_id to warehouse_wip_legacy_id;
alter table public.production_orders rename column warehouse_wip_id_new to warehouse_wip_id;
alter table public.production_orders rename column warehouse_to_id to warehouse_to_legacy_id;
alter table public.production_orders rename column warehouse_to_id_new to warehouse_to_id;
alter table public.production_orders rename column warehouse_return_id to warehouse_return_legacy_id;
alter table public.production_orders rename column warehouse_return_id_new to warehouse_return_id;

alter table public.purchase_bills rename column supplier_id to supplier_legacy_id;
alter table public.purchase_bills rename column supplier_id_new to supplier_id;
alter table public.purchase_bills rename column branch_id to branch_legacy_id;
alter table public.purchase_bills rename column branch_id_new to branch_id;
alter table public.purchase_bills rename column warehouse_id to warehouse_legacy_id;
alter table public.purchase_bills rename column warehouse_id_new to warehouse_id;
alter table public.purchase_bills rename column sales_id to sales_legacy_id;
alter table public.purchase_bills rename column sales_id_new to sales_id;

alter table public.receipts rename column customer_id to customer_legacy_id;
alter table public.receipts rename column customer_id_new to customer_id;
alter table public.receipts rename column branch_id to branch_legacy_id;
alter table public.receipts rename column branch_id_new to branch_id;

alter table public.sales_bills rename column customer_id to customer_legacy_id;
alter table public.sales_bills rename column customer_id_new to customer_id;
alter table public.sales_bills rename column branch_id to branch_legacy_id;
alter table public.sales_bills rename column branch_id_new to branch_id;
alter table public.sales_bills rename column warehouse_id to warehouse_legacy_id;
alter table public.sales_bills rename column warehouse_id_new to warehouse_id;
alter table public.sales_bills rename column sales_id to sales_legacy_id;
alter table public.sales_bills rename column sales_id_new to sales_id;

alter table public.stock_adjustments rename column branch_id to branch_legacy_id;
alter table public.stock_adjustments rename column branch_id_new to branch_id;
alter table public.stock_adjustments rename column warehouse_id to warehouse_legacy_id;
alter table public.stock_adjustments rename column warehouse_id_new to warehouse_id;

alter table public.stock_issues rename column customer_id to customer_legacy_id;
alter table public.stock_issues rename column customer_id_new to customer_id;
alter table public.stock_issues rename column branch_id to branch_legacy_id;
alter table public.stock_issues rename column branch_id_new to branch_id;
alter table public.stock_issues rename column warehouse_id to warehouse_legacy_id;
alter table public.stock_issues rename column warehouse_id_new to warehouse_id;

alter table public.stock_ledger rename column warehouse_id to warehouse_legacy_id;
alter table public.stock_ledger rename column warehouse_id_new to warehouse_id;
alter table public.stock_ledger rename column branch_id to branch_legacy_id;
alter table public.stock_ledger rename column branch_id_new to branch_id;

alter table public.supplier_advance_payments rename column branch_id to branch_legacy_id;
alter table public.supplier_advance_payments rename column branch_id_new to branch_id;
alter table public.supplier_advance_payments rename column supplier_id to supplier_legacy_id;
alter table public.supplier_advance_payments rename column supplier_id_new to supplier_id;

alter table public.supplier_bank_accounts rename column supplier_id to supplier_legacy_id;
alter table public.supplier_bank_accounts rename column supplier_id_new to supplier_id;

alter table public.suppliers rename column branch_id to branch_legacy_id;
alter table public.suppliers rename column branch_id_new to branch_id;
alter table public.suppliers rename column sales_id to sales_legacy_id;
alter table public.suppliers rename column sales_id_new to sales_id;

alter table public.trading_deals rename column supplier_id to supplier_legacy_id;
alter table public.trading_deals rename column supplier_id_new to supplier_id;
alter table public.trading_deals rename column customer_id to customer_legacy_id;
alter table public.trading_deals rename column customer_id_new to customer_id;

alter table public.users rename column branch_id to branch_legacy_id;
alter table public.users rename column branch_id_new to branch_id;

alter table public.warehouses rename column branch_id to branch_legacy_id;
alter table public.warehouses rename column branch_id_new to branch_id;

alter table public.weight_tickets rename column branch_id to branch_legacy_id;
alter table public.weight_tickets rename column branch_id_new to branch_id;
alter table public.weight_tickets rename column supplier_id to supplier_legacy_id;
alter table public.weight_tickets rename column supplier_id_new to supplier_id;
alter table public.weight_tickets rename column customer_id to customer_legacy_id;
alter table public.weight_tickets rename column customer_id_new to customer_id;

-- Preserve not-null semantics on required refs.
alter table public.app_user_branch_access alter column branch_id set not null;
alter table public.supplier_advance_payments alter column branch_id set not null;
alter table public.supplier_advance_payments alter column supplier_id set not null;
alter table public.supplier_bank_accounts alter column supplier_id set not null;
alter table public.weight_tickets alter column branch_id set not null;

-- Recreate key relational constraints on the new bigint columns.
alter table public.app_user_branch_access add constraint app_user_branch_access_pkey primary key (user_id, branch_id);
alter table public.accounts add constraint accounts_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.app_user_branch_access add constraint app_user_branch_access_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.assets add constraint assets_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.assets add constraint assets_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;
alter table public.expenses add constraint expenses_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.grade_adjustments add constraint grade_adjustments_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.payments add constraint payments_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.payments add constraint payments_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;
alter table public.po_buys add constraint po_buys_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;
alter table public.po_sells add constraint po_sells_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.production_lines add constraint production_lines_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete restrict;
alter table public.production_machines add constraint machines_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete restrict;
alter table public.production_orders add constraint production_orders_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.production_orders add constraint production_orders_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.purchase_bills add constraint purchase_bills_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.purchase_bills add constraint purchase_bills_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update cascade on delete no action;
alter table public.purchase_bills add constraint purchase_bills_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.receipts add constraint receipts_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.receipts add constraint receipts_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.sales_bills add constraint sales_bills_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.sales_bills add constraint sales_bills_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.sales_bills add constraint sales_bills_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.stock_issues add constraint stock_issues_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.stock_issues add constraint stock_issues_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.stock_issues add constraint stock_issues_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.stock_ledger add constraint stock_ledger_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.stock_ledger add constraint stock_ledger_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses(id) on update no action on delete no action;
alter table public.supplier_advance_payments add constraint supplier_advance_payments_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.supplier_advance_payments add constraint supplier_advance_payments_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;
alter table public.supplier_bank_accounts add constraint supplier_bank_accounts_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update cascade on delete cascade;
alter table public.suppliers add constraint suppliers_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.trading_deals add constraint trading_deals_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.trading_deals add constraint trading_deals_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;
alter table public.warehouses add constraint warehouses_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.weight_tickets add constraint weight_tickets_branch_id_fkey foreign key (branch_id) references public.branches(id) on update no action on delete no action;
alter table public.weight_tickets add constraint weight_tickets_customer_id_fkey foreign key (customer_id) references public.customers(id) on update no action on delete no action;
alter table public.weight_tickets add constraint weight_tickets_supplier_id_fkey foreign key (supplier_id) references public.suppliers(id) on update no action on delete no action;

-- Recreate critical indexes / uniques on the new bigint columns.
create index idx_app_user_branch_access_branch_id on public.app_user_branch_access(branch_id);
create index idx_pmt_supplier on public.payments(supplier_id);
create index production_lines_branch_id_idx on public.production_lines(branch_id);
create index production_machines_branch_id_idx on public.production_machines(branch_id);
create index idx_pb_branch on public.purchase_bills(branch_id);
create index idx_pb_supplier on public.purchase_bills(supplier_id);
create index idx_sb_branch on public.sales_bills(branch_id);
create index idx_sb_customer on public.sales_bills(customer_id);
create index idx_stock_adjustments_branch on public.stock_adjustments(branch_id);
create unique index stock_ledger_opening_unique
  on public.stock_ledger using btree (
    product_id,
    coalesce(branch_id, 0::bigint),
    coalesce(warehouse_id, 0::bigint),
    coalesce(lot_no, 'OPENING'::text),
    coalesce(output_category, 'RM'::text),
    coalesce(paid, false)
  )
  where (ref_type = 'OPENING');
create index idx_supplier_advance_payments_branch on public.supplier_advance_payments(branch_id);
create index idx_supplier_advance_payments_supplier on public.supplier_advance_payments(supplier_id);
create unique index uq_supplier_bank_accounts_supplier_account on public.supplier_bank_accounts(supplier_id, account_no);
create index idx_supplier_bank_accounts_supplier on public.supplier_bank_accounts(supplier_id);
create index idx_suppliers_branch on public.suppliers(branch_id);
create index idx_weight_tickets_branch on public.weight_tickets(branch_id);
create index idx_weight_tickets_customer on public.weight_tickets(customer_id);
create index idx_weight_tickets_supplier on public.weight_tickets(supplier_id);

drop function if exists public.__wave1_drop_fk_constraints(text, text);
drop function if exists public.__wave1_assert_backfill(text, text, text);

commit;
