create table public.payment_approval_status_logs (
  event_key text not null default ('PMALOG-'::text || gen_random_uuid()::text),
  action text not null,
  payment_approval_doc_no text not null,
  source_type text not null,
  source_id text not null,
  source_doc_no_snapshot text null,
  approved_amount_snapshot numeric not null default 0,
  from_status text null,
  to_status text not null,
  payment_doc_no text null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  payment_approval_id bigint not null references public.payment_approvals(id) on delete restrict,
  payment_id bigint null references public.payments(id) on delete set null
);

create unique index idx_payment_approval_status_logs_event_key
  on public.payment_approval_status_logs(event_key);

create index idx_payment_approval_status_logs_approval_created
  on public.payment_approval_status_logs(payment_approval_id, created_at desc);

create index idx_payment_approval_status_logs_approval_doc_no
  on public.payment_approval_status_logs(payment_approval_doc_no);

create index idx_payment_approval_status_logs_payment_doc_no
  on public.payment_approval_status_logs(payment_doc_no)
  where payment_doc_no is not null;

create index idx_payment_approval_status_logs_action
  on public.payment_approval_status_logs(action);

create table public.payment_status_logs (
  event_key text not null default ('PMTLOG-'::text || gen_random_uuid()::text),
  action text not null,
  payment_doc_no text not null,
  payment_voucher_id text null,
  supplier_code_snapshot text null,
  account_code_snapshot text null,
  amount_snapshot numeric not null default 0,
  net_amount_snapshot numeric not null default 0,
  from_status text null,
  to_status text not null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  payment_id bigint null references public.payments(id) on delete set null,
  supplier_id bigint null references public.suppliers(id) on delete set null,
  account_id bigint null references public.accounts(id) on delete set null
);

create unique index idx_payment_status_logs_event_key
  on public.payment_status_logs(event_key);

create index idx_payment_status_logs_doc_created
  on public.payment_status_logs(payment_doc_no, created_at desc);

create index idx_payment_status_logs_voucher
  on public.payment_status_logs(payment_voucher_id)
  where payment_voucher_id is not null;

create index idx_payment_status_logs_payment
  on public.payment_status_logs(payment_id)
  where payment_id is not null;

create index idx_payment_status_logs_action
  on public.payment_status_logs(action);

create table public.payment_allocations (
  allocation_key text not null,
  payment_doc_no text not null,
  payment_voucher_id text null,
  payment_approval_doc_no text not null,
  source_type text not null,
  source_doc_no_snapshot text null,
  allocated_amount numeric not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz null,
  updated_by text null,
  id bigint generated by default as identity primary key,
  payment_id bigint null references public.payments(id) on delete set null,
  payment_approval_id bigint not null references public.payment_approvals(id) on delete restrict,
  constraint payment_allocations_status_chk check (status in ('active', 'reversed'))
);

create unique index idx_payment_allocations_allocation_key
  on public.payment_allocations(allocation_key);

create index idx_payment_allocations_payment
  on public.payment_allocations(payment_id)
  where payment_id is not null;

create index idx_payment_allocations_voucher
  on public.payment_allocations(payment_voucher_id)
  where payment_voucher_id is not null;

create index idx_payment_allocations_approval
  on public.payment_allocations(payment_approval_id);

create index idx_payment_allocations_status
  on public.payment_allocations(status);

create table public.payment_account_splits (
  split_key text not null,
  payment_doc_no text not null,
  payment_voucher_id text null,
  account_code_snapshot text null,
  account_name_snapshot text null,
  amount numeric not null default 0,
  status text not null default 'active',
  bank_statement_doc_no text null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz null,
  updated_by text null,
  id bigint generated by default as identity primary key,
  payment_id bigint null references public.payments(id) on delete set null,
  account_id bigint null references public.accounts(id) on delete set null,
  bank_statement_id bigint null references public.bank_statement(id) on delete set null,
  constraint payment_account_splits_status_chk check (status in ('active', 'reversed'))
);

create unique index idx_payment_account_splits_split_key
  on public.payment_account_splits(split_key);

create index idx_payment_account_splits_payment
  on public.payment_account_splits(payment_id)
  where payment_id is not null;

create index idx_payment_account_splits_voucher
  on public.payment_account_splits(payment_voucher_id)
  where payment_voucher_id is not null;

create index idx_payment_account_splits_account
  on public.payment_account_splits(account_id)
  where account_id is not null;

create index idx_payment_account_splits_status
  on public.payment_account_splits(status);

with approval_events as (
  select
    pa.id as payment_approval_id,
    pa.doc_no as payment_approval_doc_no,
    pa.source_type,
    pa.source_id,
    pa.source_doc_no_snapshot,
    pa.approved_amount as approved_amount_snapshot,
    null::text as payment_doc_no,
    null::bigint as payment_id,
    'approved'::text as action,
    'pending'::text as from_status,
    'approved'::text as to_status,
    null::text as note,
    jsonb_build_object('source', 'migration_backfill') as meta,
    coalesce(pa.approved_at, pa.updated_at, pa.created_at, now()) as created_at,
    pa.approved_by as created_by,
    1 as sort_order
  from public.payment_approvals pa
  where pa.doc_no is not null
    and (pa.approved_at is not null or pa.status in ('approved', 'paid', 'voided'))

  union all

  select
    pa.id as payment_approval_id,
    pa.doc_no as payment_approval_doc_no,
    pa.source_type,
    pa.source_id,
    pa.source_doc_no_snapshot,
    pa.approved_amount as approved_amount_snapshot,
    p.doc_no as payment_doc_no,
    p.id as payment_id,
    'paid'::text as action,
    'approved'::text as from_status,
    'paid'::text as to_status,
    null::text as note,
    jsonb_build_object('source', 'migration_backfill', 'voucherId', p.voucher_id) as meta,
    coalesce(pa.paid_at, p.created_at, pa.updated_at, now()) as created_at,
    coalesce(p.created_by, pa.approved_by) as created_by,
    2 as sort_order
  from public.payment_approvals pa
  left join lateral (
    select p2.id, p2.doc_no, p2.voucher_id, p2.created_at, p2.created_by
    from public.payments p2
    where p2.payment_approval_id = pa.id
    order by p2.created_at desc nulls last, p2.id desc
    limit 1
  ) p on true
  where pa.doc_no is not null
    and (pa.paid_at is not null or pa.status = 'paid')

  union all

  select
    pa.id as payment_approval_id,
    pa.doc_no as payment_approval_doc_no,
    pa.source_type,
    pa.source_id,
    pa.source_doc_no_snapshot,
    pa.approved_amount as approved_amount_snapshot,
    p.doc_no as payment_doc_no,
    p.id as payment_id,
    case
      when p.id is not null then 'reversed_by_payment_cancel'
      else 'voided_before_payment'
    end::text as action,
    case
      when p.id is not null then 'paid'
      else 'approved'
    end::text as from_status,
    'voided'::text as to_status,
    pa.void_reason as note,
    jsonb_build_object('source', 'migration_backfill', 'voucherId', p.voucher_id) as meta,
    coalesce(pa.voided_at, pa.updated_at, now()) as created_at,
    coalesce(pa.voided_by, p.updated_by, pa.approved_by) as created_by,
    3 as sort_order
  from public.payment_approvals pa
  left join lateral (
    select p2.id, p2.doc_no, p2.voucher_id, p2.updated_by
    from public.payments p2
    where p2.payment_approval_id = pa.id
    order by p2.updated_at desc nulls last, p2.created_at desc nulls last, p2.id desc
    limit 1
  ) p on true
  where pa.doc_no is not null
    and (pa.status = 'voided' or pa.voided_at is not null)
),
numbered_approval_events as (
  select
    approval_events.*,
    row_number() over (
      partition by payment_approval_id
      order by created_at, sort_order, payment_id nulls first
    ) as seq
  from approval_events
)
insert into public.payment_approval_status_logs (
  event_key,
  action,
  payment_approval_doc_no,
  source_type,
  source_id,
  source_doc_no_snapshot,
  approved_amount_snapshot,
  from_status,
  to_status,
  payment_doc_no,
  note,
  meta,
  created_at,
  created_by,
  payment_approval_id,
  payment_id
)
select
  'PMALOG-' || payment_approval_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  payment_approval_doc_no,
  source_type,
  source_id,
  source_doc_no_snapshot,
  approved_amount_snapshot,
  from_status,
  to_status,
  payment_doc_no,
  note,
  meta,
  created_at,
  created_by,
  payment_approval_id,
  payment_id
from numbered_approval_events;

with payment_groups as (
  select
    coalesce(p.voucher_id, p.doc_no) as voucher_key,
    (array_agg(p.id order by p.created_at nulls first, p.id))[1] as payment_id,
    (array_agg(p.doc_no order by p.created_at nulls first, p.id))[1] as payment_doc_no,
    (array_agg(p.created_by order by p.created_at nulls first, p.id))[1] as created_by,
    (array_agg(p.updated_by order by p.updated_at desc nulls last, p.id desc))[1] as updated_by,
    min(coalesce(p.created_at, now())) as created_at,
    max(coalesce(p.updated_at, p.created_at, now())) as updated_at,
    sum(coalesce(p.amount, 0)) as amount_snapshot,
    sum(coalesce(p.net_amount, 0)) as net_amount_snapshot,
    bool_or(coalesce(p.status, 'active') = 'cancelled') as has_cancelled,
    (array_agg(p.supplier_id order by p.created_at nulls first, p.id))[1] as supplier_id,
    (array_agg(p.account_id order by p.created_at nulls first, p.id))[1] as account_id
  from public.payments p
  group by coalesce(p.voucher_id, p.doc_no)
),
payment_events as (
  select
    pg.*,
    'posted'::text as action,
    null::text as from_status,
    'active'::text as to_status,
    null::text as note,
    jsonb_build_object('source', 'migration_backfill') as meta,
    pg.created_at as event_created_at,
    pg.created_by as event_created_by,
    1 as sort_order
  from payment_groups pg

  union all

  select
    pg.*,
    'cancelled'::text as action,
    'active'::text as from_status,
    'cancelled'::text as to_status,
    null::text as note,
    jsonb_build_object('source', 'migration_backfill') as meta,
    pg.updated_at as event_created_at,
    pg.updated_by as event_created_by,
    2 as sort_order
  from payment_groups pg
  where pg.has_cancelled
),
numbered_payment_events as (
  select
    payment_events.*,
    s.code as supplier_code_snapshot,
    a.code as account_code_snapshot,
    row_number() over (
      partition by voucher_key
      order by event_created_at, sort_order
    ) as seq
  from payment_events
  left join public.suppliers s on s.id = payment_events.supplier_id
  left join public.accounts a on a.id = payment_events.account_id
)
insert into public.payment_status_logs (
  event_key,
  action,
  payment_doc_no,
  payment_voucher_id,
  supplier_code_snapshot,
  account_code_snapshot,
  amount_snapshot,
  net_amount_snapshot,
  from_status,
  to_status,
  note,
  meta,
  created_at,
  created_by,
  payment_id,
  supplier_id,
  account_id
)
select
  'PMTLOG-' || voucher_key || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  payment_doc_no,
  voucher_key,
  supplier_code_snapshot,
  account_code_snapshot,
  amount_snapshot,
  net_amount_snapshot,
  from_status,
  to_status,
  note,
  meta,
  event_created_at,
  event_created_by,
  payment_id,
  supplier_id,
  account_id
from numbered_payment_events;

insert into public.payment_allocations (
  allocation_key,
  payment_doc_no,
  payment_voucher_id,
  payment_approval_doc_no,
  source_type,
  source_doc_no_snapshot,
  allocated_amount,
  status,
  created_at,
  created_by,
  updated_at,
  updated_by,
  payment_id,
  payment_approval_id
)
select
  'PMTALLOC-' || p.doc_no || '-' || p.id::text as allocation_key,
  p.doc_no as payment_doc_no,
  coalesce(p.voucher_id, p.doc_no) as payment_voucher_id,
  coalesce(pa.doc_no, 'PMA-' || pa.id::text) as payment_approval_doc_no,
  pa.source_type,
  pa.source_doc_no_snapshot,
  coalesce(p.amount, 0) + coalesce(p.withholding_tax, 0) + coalesce(p.discount, 0) as allocated_amount,
  case
    when coalesce(p.status, 'active') = 'cancelled' then 'reversed'
    else 'active'
  end as status,
  coalesce(p.created_at, now()) as created_at,
  p.created_by,
  p.updated_at,
  p.updated_by,
  p.id as payment_id,
  pa.id as payment_approval_id
from public.payments p
join public.payment_approvals pa on pa.id = p.payment_approval_id
where p.payment_approval_id is not null;

with payment_groups as (
  select
    coalesce(p.voucher_id, p.doc_no) as voucher_key,
    (array_agg(p.id order by p.created_at nulls first, p.id))[1] as payment_id,
    (array_agg(p.doc_no order by p.created_at nulls first, p.id))[1] as payment_doc_no,
    bool_or(coalesce(p.status, 'active') = 'cancelled') as has_cancelled
  from public.payments p
  group by coalesce(p.voucher_id, p.doc_no)
),
statement_splits as (
  select
    'PMTSPLIT-' || bs.doc_no as split_key,
    pg.payment_doc_no,
    pg.voucher_key as payment_voucher_id,
    a.code as account_code_snapshot,
    a.name as account_name_snapshot,
    coalesce(bs.amount_out, 0) as amount,
    case
      when pg.has_cancelled then 'reversed'
      else 'active'
    end as status,
    bs.doc_no as bank_statement_doc_no,
    coalesce(bs.created_at, now()) as created_at,
    bs.created_by,
    bs.updated_at,
    bs.updated_by,
    pg.payment_id,
    bs.account_id,
    bs.id as bank_statement_id
  from public.bank_statement bs
  join payment_groups pg on pg.voucher_key = bs.ref_id
  left join public.accounts a on a.id = bs.account_id
  where bs.ref_type = 'PMT'
),
fallback_splits as (
  select
    'PMTSPLIT-' || p.doc_no || '-' || coalesce(p.voucher_id, p.id::text) || '-' || coalesce(p.account_id::text, 'NA') || '-' || coalesce(p.status, 'active') as split_key,
    p.doc_no as payment_doc_no,
    coalesce(p.voucher_id, p.doc_no) as payment_voucher_id,
    a.code as account_code_snapshot,
    a.name as account_name_snapshot,
    sum(coalesce(p.net_amount, 0)) as amount,
    case
      when coalesce(p.status, 'active') = 'cancelled' then 'reversed'
      else 'active'
    end as status,
    null::text as bank_statement_doc_no,
    min(coalesce(p.created_at, now())) as created_at,
    (array_agg(p.created_by order by p.created_at nulls first, p.id))[1] as created_by,
    max(p.updated_at) as updated_at,
    (array_agg(p.updated_by order by p.updated_at desc nulls last, p.id desc))[1] as updated_by,
    min(p.id) as payment_id,
    p.account_id,
    null::bigint as bank_statement_id
  from public.payments p
  left join public.accounts a on a.id = p.account_id
  where not exists (
    select 1
    from public.bank_statement bs
    where bs.ref_type = 'PMT'
      and bs.ref_id = coalesce(p.voucher_id, p.doc_no)
  )
  group by
    p.doc_no,
    coalesce(p.voucher_id, p.doc_no),
    coalesce(p.voucher_id, p.id::text),
    p.account_id,
    a.code,
    a.name,
    coalesce(p.status, 'active')
)
insert into public.payment_account_splits (
  split_key,
  payment_doc_no,
  payment_voucher_id,
  account_code_snapshot,
  account_name_snapshot,
  amount,
  status,
  bank_statement_doc_no,
  created_at,
  created_by,
  updated_at,
  updated_by,
  payment_id,
  account_id,
  bank_statement_id
)
select *
from statement_splits

union all

select *
from fallback_splits;
