BEGIN;

CREATE TABLE IF NOT EXISTS public.account_currency_balances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  currency_code text NOT NULL REFERENCES public.currencies(code),
  opening_balance numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_account_currency_balances_account_currency UNIQUE (account_id, currency_code)
);

CREATE INDEX IF NOT EXISTS idx_account_currency_balances_currency
  ON public.account_currency_balances (currency_code);

INSERT INTO public.account_currency_balances (account_id, currency_code, opening_balance)
SELECT a.id, upper(coalesce(nullif(trim(a.currency), ''), 'THB')), coalesce(a.opening_balance, 0)
FROM public.accounts a
JOIN public.currencies c ON c.code = upper(coalesce(nullif(trim(a.currency), ''), 'THB'))
ON CONFLICT (account_id, currency_code) DO NOTHING;

COMMIT;
