create table public.supplier_advance_status_logs (
  event_key text not null default ('ADVLOG-'::text || gen_random_uuid()::text),
  action text not null,
  advance_doc_no text not null,
  amount_snapshot numeric not null default 0,
  allocated_amount_snapshot numeric not null default 0,
  remaining_amount_snapshot numeric not null default 0,
  from_status text null,
  to_status text not null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  advance_payment_id bigint not null references public.supplier_advance_payments(id) on delete restrict
);

create unique index idx_supplier_advance_status_logs_event_key
  on public.supplier_advance_status_logs(event_key);

create index idx_supplier_advance_status_logs_advance_created
  on public.supplier_advance_status_logs(advance_payment_id, created_at desc);

create index idx_supplier_advance_status_logs_action
  on public.supplier_advance_status_logs(action);

create table public.supplier_advance_allocation_logs (
  event_key text not null default ('ADVALLOC-'::text || gen_random_uuid()::text),
  action text not null,
  advance_doc_no text not null,
  purchase_bill_doc_no text null,
  allocation_key text null,
  allocated_amount numeric not null default 0,
  from_remaining_amount numeric null,
  to_remaining_amount numeric null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  advance_payment_id bigint not null references public.supplier_advance_payments(id) on delete restrict,
  purchase_bill_id bigint null references public.purchase_bills(id) on delete set null,
  allocation_id bigint null references public.supplier_advance_allocations(id) on delete set null
);

create unique index idx_supplier_advance_allocation_logs_event_key
  on public.supplier_advance_allocation_logs(event_key);

create index idx_supplier_advance_allocation_logs_advance_created
  on public.supplier_advance_allocation_logs(advance_payment_id, created_at desc);

create index idx_supplier_advance_allocation_logs_purchase_bill
  on public.supplier_advance_allocation_logs(purchase_bill_id);

create index idx_supplier_advance_allocation_logs_allocation
  on public.supplier_advance_allocation_logs(allocation_id);

create index idx_supplier_advance_allocation_logs_allocation_key
  on public.supplier_advance_allocation_logs(allocation_key);

with status_events as (
  select
    sap.id as advance_payment_id,
    sap.doc_no as advance_doc_no,
    'created'::text as action,
    null::text as from_status,
    'pending_approval'::text as to_status,
    sap.amount as amount_snapshot,
    sap.allocated_amount as allocated_amount_snapshot,
    sap.remaining_amount as remaining_amount_snapshot,
    sap.created_at as created_at,
    sap.created_by as created_by,
    jsonb_build_object('source', 'migration_backfill') as meta,
    1 as sort_order
  from public.supplier_advance_payments sap

  union all

  select
    sap.id as advance_payment_id,
    sap.doc_no as advance_doc_no,
    case
      when sap.status = 'approved' then 'approved'
      when sap.status = 'paid' then 'paid'
      when sap.status = 'partially_allocated' then 'partially_allocated'
      when sap.status = 'allocated' then 'allocated'
      when sap.status = 'refunding' then 'refund_required'
      when sap.status = 'refunded' then 'refunded'
      else 'status_synced'
    end as action,
    'pending_approval'::text as from_status,
    sap.status as to_status,
    sap.amount as amount_snapshot,
    sap.allocated_amount as allocated_amount_snapshot,
    sap.remaining_amount as remaining_amount_snapshot,
    coalesce(sap.updated_at, sap.created_at, now()) as created_at,
    sap.updated_by as created_by,
    jsonb_build_object('source', 'migration_backfill', 'reason', 'current_status_snapshot') as meta,
    2 as sort_order
  from public.supplier_advance_payments sap
  where sap.status is not null
    and sap.status <> 'pending_approval'
    and sap.status <> 'cancelled'

  union all

  select
    sap.id as advance_payment_id,
    sap.doc_no as advance_doc_no,
    'cancelled'::text as action,
    'pending_approval'::text as from_status,
    'cancelled'::text as to_status,
    sap.amount as amount_snapshot,
    sap.allocated_amount as allocated_amount_snapshot,
    sap.remaining_amount as remaining_amount_snapshot,
    coalesce(sap.cancelled_at, sap.updated_at, sap.created_at, now()) as created_at,
    coalesce(sap.cancelled_by, sap.updated_by) as created_by,
    jsonb_build_object('source', 'migration_backfill', 'cancelReason', sap.cancel_reason) as meta,
    3 as sort_order
  from public.supplier_advance_payments sap
  where sap.status = 'cancelled'
     or sap.cancelled_at is not null
),
numbered_status_events as (
  select
    status_events.*,
    row_number() over (
      partition by advance_payment_id
      order by created_at, sort_order, action
    ) as seq
  from status_events
)
insert into public.supplier_advance_status_logs (
  event_key,
  action,
  advance_doc_no,
  amount_snapshot,
  allocated_amount_snapshot,
  remaining_amount_snapshot,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  advance_payment_id
)
select
  'ADVLOG-' || advance_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  advance_doc_no,
  amount_snapshot,
  allocated_amount_snapshot,
  remaining_amount_snapshot,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  advance_payment_id
from numbered_status_events;

with allocation_events as (
  select
    saa.id as allocation_id,
    saa.allocation_key,
    saa.advance_payment_id,
    sap.doc_no as advance_doc_no,
    saa.purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    'allocated_to_purchase_bill'::text as action,
    saa.allocated_amount,
    coalesce(saa.allocated_at, saa.created_at, now()) as created_at,
    saa.allocated_by as created_by,
    jsonb_build_object('source', 'migration_backfill') as meta,
    1 as sort_order
  from public.supplier_advance_allocations saa
  join public.supplier_advance_payments sap on sap.id = saa.advance_payment_id
  join public.purchase_bills pb on pb.id = saa.purchase_bill_id

  union all

  select
    saa.id as allocation_id,
    saa.allocation_key,
    saa.advance_payment_id,
    sap.doc_no as advance_doc_no,
    saa.purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    'released_from_purchase_bill'::text as action,
    saa.allocated_amount,
    coalesce(saa.voided_at, saa.updated_at, now()) as created_at,
    saa.voided_by as created_by,
    jsonb_build_object('source', 'migration_backfill', 'voidReason', saa.void_reason) as meta,
    2 as sort_order
  from public.supplier_advance_allocations saa
  join public.supplier_advance_payments sap on sap.id = saa.advance_payment_id
  join public.purchase_bills pb on pb.id = saa.purchase_bill_id
  where saa.status = 'voided'
     or saa.voided_at is not null
),
running_allocation_events as (
  select
    allocation_events.*,
    sap.amount as advance_amount,
    coalesce(sum(
      case
        when allocation_events.action = 'released_from_purchase_bill' then -allocation_events.allocated_amount
        else allocation_events.allocated_amount
      end
    ) over (
      partition by allocation_events.advance_payment_id
      order by allocation_events.created_at, allocation_events.sort_order, allocation_events.allocation_id
      rows between unbounded preceding and 1 preceding
    ), 0) as consumed_before,
    row_number() over (
      partition by allocation_events.advance_payment_id
      order by allocation_events.created_at, allocation_events.sort_order, allocation_events.allocation_id
    ) as seq
  from allocation_events
  join public.supplier_advance_payments sap on sap.id = allocation_events.advance_payment_id
)
insert into public.supplier_advance_allocation_logs (
  event_key,
  action,
  advance_doc_no,
  purchase_bill_doc_no,
  allocation_key,
  allocated_amount,
  from_remaining_amount,
  to_remaining_amount,
  meta,
  created_at,
  created_by,
  advance_payment_id,
  purchase_bill_id,
  allocation_id
)
select
  'ADVALLOC-' || advance_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  advance_doc_no,
  purchase_bill_doc_no,
  allocation_key,
  allocated_amount,
  greatest(0, advance_amount - consumed_before) as from_remaining_amount,
  greatest(
    0,
    advance_amount - consumed_before - case when action = 'released_from_purchase_bill' then -allocated_amount else allocated_amount end
  ) as to_remaining_amount,
  meta,
  created_at,
  created_by,
  advance_payment_id,
  purchase_bill_id,
  allocation_id
from running_allocation_events;
