alter table public.weight_ticket_image_assets
  add column if not exists download_storage_key text,
  add column if not exists download_status text not null default 'queued',
  add column if not exists download_attempt_count integer not null default 0,
  add column if not exists download_next_retry_at timestamptz not null default now(),
  add column if not exists download_locked_at timestamptz,
  add column if not exists download_locked_by text,
  add column if not exists download_width integer,
  add column if not exists download_height integer,
  add column if not exists download_byte_size bigint,
  add column if not exists download_last_error text;

update public.weight_ticket_image_assets
set download_storage_key = case
  when original_storage_key ~ '\\.[^./]+$'
    then regexp_replace(original_storage_key, '\\.[^./]+$', '.download.jpg')
  else original_storage_key || '.download.jpg'
end
where download_storage_key is null;

alter table public.weight_ticket_image_assets
  alter column download_storage_key set not null;

create unique index if not exists weight_ticket_image_assets_download_idx
  on public.weight_ticket_image_assets (bucket, download_storage_key);

create index if not exists weight_ticket_image_assets_download_pending_idx
  on public.weight_ticket_image_assets (download_status, download_next_retry_at);

insert into public.system_settings (key, value, description)
values
  ('WEIGHT_TICKET_DOWNLOAD_MAX_DIMENSION', '1600', 'Maximum long-side pixels for downloadable WTI/WTO image derivatives'),
  ('WEIGHT_TICKET_DOWNLOAD_JPEG_QUALITY', '88', 'JPEG quality for downloadable WTI/WTO image derivatives')
on conflict (key) do nothing;

create table if not exists public.weight_ticket_image_download_artifacts (
  id bigint generated by default as identity primary key,
  bucket text not null,
  storage_key text not null unique,
  expires_at timestamptz not null,
  created_by text,
  created_at timestamptz not null default now()
);

alter table public.weight_ticket_image_download_artifacts enable row level security;

create index if not exists weight_ticket_image_download_artifacts_expiry_idx
  on public.weight_ticket_image_download_artifacts (expires_at);
