create table public.po_buy_allocation_logs (
  event_key text not null default ('POALLOC-'::text || gen_random_uuid()::text),
  action text not null,
  po_buy_doc_no text not null,
  purchase_bill_doc_no text null,
  purchase_bill_line_no integer null,
  product_code_snapshot text null,
  product_name_snapshot text null,
  allocated_qty numeric not null default 0,
  allocated_amount numeric not null default 0,
  unit_price_snapshot numeric not null default 0,
  from_remaining_qty numeric null,
  to_remaining_qty numeric null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  po_buy_id bigint not null references public.po_buys(id) on delete restrict,
  purchase_bill_id bigint null references public.purchase_bills(id) on delete set null,
  purchase_bill_item_id bigint null references public.purchase_bill_items(id) on delete set null,
  product_id bigint null references public.products(id) on delete set null
);

create unique index idx_po_buy_allocation_logs_event_key
  on public.po_buy_allocation_logs(event_key);

create index idx_po_buy_allocation_logs_po_created
  on public.po_buy_allocation_logs(po_buy_id, created_at desc);

create index idx_po_buy_allocation_logs_purchase_bill
  on public.po_buy_allocation_logs(purchase_bill_id);

create index idx_po_buy_allocation_logs_product
  on public.po_buy_allocation_logs(product_id);

with active_allocations as (
  select
    pba.id,
    pba.po_buy_id,
    po.doc_no as po_buy_doc_no,
    pba.purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    pba.purchase_bill_item_id,
    pbi.line_no as purchase_bill_line_no,
    pbi.product_id,
    pbi.product_code as product_code_snapshot,
    pbi.product_name as product_name_snapshot,
    pba.allocated_qty,
    pba.allocated_amount,
    pba.unit_price_snapshot,
    pba.created_at,
    pba.created_by,
    row_number() over (
      partition by pba.po_buy_id
      order by pba.created_at, pb.doc_no, pbi.line_no, pba.id
    ) as seq
  from public.purchase_bill_po_allocations pba
  join public.po_buys po on po.id = pba.po_buy_id
  join public.purchase_bills pb on pb.id = pba.purchase_bill_id
  join public.purchase_bill_items pbi on pbi.id = pba.purchase_bill_item_id
  where coalesce(pb.status, '') <> 'cancelled'
)
insert into public.po_buy_allocation_logs (
  event_key,
  action,
  po_buy_doc_no,
  purchase_bill_doc_no,
  purchase_bill_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_amount,
  unit_price_snapshot,
  meta,
  created_at,
  created_by,
  po_buy_id,
  purchase_bill_id,
  purchase_bill_item_id,
  product_id
)
select
  'POALLOC-' || po_buy_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  'allocated_to_purchase_bill' as action,
  po_buy_doc_no,
  purchase_bill_doc_no,
  purchase_bill_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_amount,
  unit_price_snapshot,
  jsonb_build_object('source', 'migration_backfill', 'activeAllocationId', id::text) as meta,
  coalesce(created_at, now()),
  created_by,
  po_buy_id,
  purchase_bill_id,
  purchase_bill_item_id,
  product_id
from active_allocations;
