create table public.weight_ticket_usage_logs (
  event_key text not null default ('WTUSE-'::text || gen_random_uuid()::text),
  action text not null,
  weight_ticket_doc_no text not null,
  doc_type text not null default 'WTI',
  target_type text not null,
  target_id bigint null,
  target_doc_no text null,
  target_line_no integer null,
  product_code_snapshot text null,
  product_name_snapshot text null,
  allocated_qty numeric not null default 0,
  allocated_gross_weight numeric not null default 0,
  allocated_deduct_weight numeric not null default 0,
  allocated_net_weight numeric not null default 0,
  from_remaining_weight numeric null,
  to_remaining_weight numeric null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  weight_ticket_id bigint not null references public.weight_tickets(id) on delete restrict,
  weight_ticket_product_summary_id bigint null references public.weight_ticket_product_summaries(id) on delete set null,
  product_id bigint null references public.products(id) on delete set null,
  purchase_bill_id bigint null references public.purchase_bills(id) on delete set null,
  purchase_bill_item_id bigint null references public.purchase_bill_items(id) on delete set null
);

create unique index idx_weight_ticket_usage_logs_event_key
  on public.weight_ticket_usage_logs(event_key);

create index idx_weight_ticket_usage_logs_ticket_created
  on public.weight_ticket_usage_logs(weight_ticket_id, created_at desc);

create index idx_weight_ticket_usage_logs_summary
  on public.weight_ticket_usage_logs(weight_ticket_product_summary_id);

create index idx_weight_ticket_usage_logs_target
  on public.weight_ticket_usage_logs(target_type, target_id);

create index idx_weight_ticket_usage_logs_purchase_bill
  on public.weight_ticket_usage_logs(purchase_bill_id);

create index idx_weight_ticket_usage_logs_product
  on public.weight_ticket_usage_logs(product_id);

with active_allocations as (
  select
    pbra.id,
    pbra.weight_ticket_id,
    wt.doc_no as weight_ticket_doc_no,
    wt.doc_type,
    pbra.weight_ticket_product_summary_id,
    wts.product_id,
    p.code as product_code_snapshot,
    coalesce(pbi.product_name, wts.product_name, p.name) as product_name_snapshot,
    pbra.purchase_bill_id,
    pb.doc_no as purchase_bill_doc_no,
    pbra.purchase_bill_item_id,
    pbi.line_no as purchase_bill_line_no,
    pbra.allocated_qty,
    pbra.allocated_gross_weight,
    pbra.allocated_deduct_weight,
    coalesce(wts.net_weight, 0) as source_net_weight,
    pbra.created_at,
    pbra.created_by,
    row_number() over (
      partition by pbra.weight_ticket_id
      order by pbra.created_at, pb.doc_no, pbi.line_no, pbra.id
    ) as ticket_seq,
    coalesce(sum(pbra.allocated_qty) over (
      partition by pbra.weight_ticket_product_summary_id
      order by pbra.created_at, pb.doc_no, pbi.line_no, pbra.id
      rows between unbounded preceding and 1 preceding
    ), 0) as allocated_before
  from public.purchase_bill_receipt_allocations pbra
  join public.weight_tickets wt on wt.id = pbra.weight_ticket_id
  join public.weight_ticket_product_summaries wts on wts.id = pbra.weight_ticket_product_summary_id
  left join public.products p on p.id = wts.product_id
  join public.purchase_bills pb on pb.id = pbra.purchase_bill_id
  join public.purchase_bill_items pbi on pbi.id = pbra.purchase_bill_item_id
  where wt.doc_type = 'WTI'
    and coalesce(pb.status, '') <> 'cancelled'
)
insert into public.weight_ticket_usage_logs (
  event_key,
  action,
  weight_ticket_doc_no,
  doc_type,
  target_type,
  target_id,
  target_doc_no,
  target_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_gross_weight,
  allocated_deduct_weight,
  allocated_net_weight,
  from_remaining_weight,
  to_remaining_weight,
  meta,
  created_at,
  created_by,
  weight_ticket_id,
  weight_ticket_product_summary_id,
  product_id,
  purchase_bill_id,
  purchase_bill_item_id
)
select
  'WTUSE-' || weight_ticket_doc_no || '-' || lpad(ticket_seq::text, 4, '0') as event_key,
  'allocated_to_purchase_bill' as action,
  weight_ticket_doc_no,
  doc_type,
  'PURCHASE_BILL' as target_type,
  purchase_bill_id as target_id,
  purchase_bill_doc_no as target_doc_no,
  purchase_bill_line_no as target_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_gross_weight,
  allocated_deduct_weight,
  allocated_qty as allocated_net_weight,
  greatest(0, source_net_weight - allocated_before) as from_remaining_weight,
  greatest(0, source_net_weight - allocated_before - allocated_qty) as to_remaining_weight,
  jsonb_build_object('source', 'migration_backfill', 'activeAllocationId', id::text) as meta,
  coalesce(created_at, now()),
  created_by,
  weight_ticket_id,
  weight_ticket_product_summary_id,
  product_id,
  purchase_bill_id,
  purchase_bill_item_id
from active_allocations;
