alter table public.weight_tickets
  add column if not exists draft_version integer not null default 0;

alter table public.weight_ticket_lines
  add column if not exists draft_version integer not null default 0;

create table if not exists public.weight_ticket_draft_operations (
  id bigint generated by default as identity primary key,
  weight_ticket_id bigint not null references public.weight_tickets(id) on delete cascade,
  weight_ticket_line_id bigint references public.weight_ticket_lines(id) on delete set null,
  operation_id text not null,
  actor text not null,
  action text not null,
  document_version_before integer not null,
  document_version_after integer not null,
  line_version_before integer,
  line_version_after integer,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_weight_ticket_draft_operations_ticket_operation
  on public.weight_ticket_draft_operations(weight_ticket_id, operation_id);

create index if not exists idx_weight_ticket_draft_operations_ticket_created
  on public.weight_ticket_draft_operations(weight_ticket_id, created_at);

create index if not exists idx_weight_ticket_draft_operations_line
  on public.weight_ticket_draft_operations(weight_ticket_line_id)
  where weight_ticket_line_id is not null;

comment on column public.weight_tickets.draft_version is
  'Monotonic version for concurrent WTI draft operations; incremented after each committed line operation.';

comment on column public.weight_ticket_lines.draft_version is
  'Optimistic concurrency version for a weight-ticket line; used by WTI draft update/delete operations.';
