create table public.weight_ticket_image_assets (
  id bigint generated by default as identity primary key,
  bucket text not null,
  original_storage_key text not null,
  thumbnail_storage_key text not null,
  file_name text not null,
  mime_type text,
  byte_size bigint,
  thumbnail_status text not null default 'queued',
  attempt_count integer not null default 0,
  next_retry_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  source_width integer,
  source_height integer,
  thumbnail_width integer,
  thumbnail_height integer,
  last_error text,
  uploaded_by text,
  attached_ticket_id bigint references public.weight_tickets(id) on delete set null,
  attached_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weight_ticket_image_assets_status_check
    check (thumbnail_status in ('queued', 'processing', 'ready', 'failed')),
  constraint weight_ticket_image_assets_byte_size_check
    check (byte_size is null or byte_size > 0),
  constraint weight_ticket_image_assets_attempt_count_check
    check (attempt_count >= 0),
  constraint weight_ticket_image_assets_dimensions_check
    check (
      (source_width is null or source_width > 0)
      and (source_height is null or source_height > 0)
      and (thumbnail_width is null or thumbnail_width > 0)
      and (thumbnail_height is null or thumbnail_height > 0)
    ),
  constraint weight_ticket_image_assets_original_key unique (bucket, original_storage_key),
  constraint weight_ticket_image_assets_thumbnail_key unique (bucket, thumbnail_storage_key)
);

create index weight_ticket_image_assets_pending_idx
  on public.weight_ticket_image_assets (thumbnail_status, next_retry_at);
create index weight_ticket_image_assets_owner_idx
  on public.weight_ticket_image_assets (uploaded_by, created_at);
create index weight_ticket_image_assets_ticket_idx
  on public.weight_ticket_image_assets (attached_ticket_id);

alter table public.weight_ticket_image_assets enable row level security;

insert into public.system_settings (key, description, value)
values
  ('WEIGHT_TICKET_IMAGE_MAX_UPLOAD_BYTES', 'Maximum original WTI/WTO image upload size in bytes', '10485760'),
  ('WEIGHT_TICKET_IMAGE_UPLOAD_CONCURRENCY', 'Maximum concurrent original image uploads in one WTI/WTO selection batch', '6'),
  ('WEIGHT_TICKET_THUMBNAIL_MAX_DIMENSION', 'Maximum width or height of generated WTI/WTO thumbnails in pixels', '960'),
  ('WEIGHT_TICKET_THUMBNAIL_WEBP_QUALITY', 'WebP thumbnail quality from 1 to 100', '90'),
  ('WEIGHT_TICKET_THUMBNAIL_MAX_SOURCE_PIXELS', 'Maximum decoded source pixels accepted by the thumbnail worker', '40000000'),
  ('WEIGHT_TICKET_THUMBNAIL_MAX_ATTEMPTS', 'Maximum attempts for each WTI/WTO thumbnail job', '3'),
  ('WEIGHT_TICKET_THUMBNAIL_RETRY_DELAY_SECONDS', 'Retry delay for a failed WTI/WTO thumbnail job', '30'),
  ('WEIGHT_TICKET_THUMBNAIL_LOCK_TIMEOUT_SECONDS', 'Lease timeout for a WTI/WTO thumbnail worker', '300'),
  ('WEIGHT_TICKET_THUMBNAIL_PREVIEW_POLL_SECONDS', 'Polling interval while WTI/WTO thumbnails are still processing', '2'),
  ('WEIGHT_TICKET_THUMBNAIL_DRAIN_BATCH_SIZE', 'Maximum WTI/WTO thumbnail/cleanup assets handled by one maintenance invocation', '20'),
  ('WEIGHT_TICKET_IMAGE_PREVIEW_TTL_SECONDS', 'Signed URL lifetime for private WTI/WTO thumbnails', '3600'),
  ('WEIGHT_TICKET_IMAGE_ORPHAN_RETENTION_SECONDS', 'Retention before unattached WTI/WTO image assets become cleanup eligible', '86400')
on conflict (key) do update
set description = excluded.description,
    value = case
      when nullif(trim(public.system_settings.value), '') is null then excluded.value
      else public.system_settings.value
    end;

do $$
declare
  image_record record;
  image_json jsonb;
  image_bucket text;
  image_original_key text;
  image_thumbnail_key text;
  image_file_name text;
  invalid_count integer := 0;
  missing_original_count integer := 0;
begin
  for image_record in
    select ticket_id, raw_value
    from (
      select wt.id as ticket_id, vehicle_image.raw_value
      from public.weight_tickets wt
      cross join lateral unnest(wt.vehicle_image_names) as vehicle_image(raw_value)
      union all
      select wtl.weight_ticket_id as ticket_id, line_image.raw_value
      from public.weight_ticket_lines wtl
      cross join lateral unnest(wtl.image_names) as line_image(raw_value)
    ) existing_images
  loop
    begin
      image_json := image_record.raw_value::jsonb;
    exception when others then
      invalid_count := invalid_count + 1;
      image_json := null;
    end;

    if image_json is not null then
      image_bucket := nullif(trim(image_json ->> 'bucket'), '');
      image_original_key := nullif(trim(image_json ->> 'storageKey'), '');
      image_thumbnail_key := nullif(trim(image_json ->> 'thumbnailStorageKey'), '');
      image_file_name := nullif(trim(image_json ->> 'fileName'), '');

      if image_bucket is null
        or image_original_key is null
        or image_thumbnail_key is null
        or image_file_name is null then
        invalid_count := invalid_count + 1;
      elsif not exists (
        select 1 from storage.objects
        where bucket_id = image_bucket and name = image_original_key
      ) then
        missing_original_count := missing_original_count + 1;
      else
        insert into public.weight_ticket_image_assets (
          bucket,
          original_storage_key,
          thumbnail_storage_key,
          file_name,
          thumbnail_status,
          attached_ticket_id,
          attached_at
        ) values (
          image_bucket,
          image_original_key,
          image_thumbnail_key,
          image_file_name,
          case when exists (
            select 1 from storage.objects
            where bucket_id = image_bucket and name = image_thumbnail_key
          ) then 'ready' else 'queued' end,
          image_record.ticket_id,
          now()
        )
        on conflict (bucket, original_storage_key) do update
        set attached_ticket_id = coalesce(public.weight_ticket_image_assets.attached_ticket_id, excluded.attached_ticket_id),
            attached_at = coalesce(public.weight_ticket_image_assets.attached_at, excluded.attached_at),
            thumbnail_status = case
              when public.weight_ticket_image_assets.thumbnail_status = 'ready'
                and exists (select 1 from storage.objects where bucket_id = public.weight_ticket_image_assets.bucket and name = public.weight_ticket_image_assets.thumbnail_storage_key)
                then 'ready'
              else excluded.thumbnail_status
            end,
            updated_at = now();
      end if;
    end if;
  end loop;

  if invalid_count > 0 or missing_original_count > 0 then
    raise exception 'WTI/WTO image backfill blocked: invalid_or_legacy=% missing_original_object=%; run the image audit and fix source data before promotion', invalid_count, missing_original_count;
  end if;
end $$;
