begin;

create table if not exists public.godowns (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  active boolean default true,
  in_charge text,
  phone text,
  supported_processes text[] not null default '{}',
  target_sort_kg numeric,
  target_bale_count integer,
  max_capacity_kg numeric,
  branch_id bigint references public.branches(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint godowns_code_kd_check check (code ~ '^KD-[0-9]+$')
);

create index if not exists godowns_branch_id_idx on public.godowns(branch_id);

insert into public.godowns (
  code, name, active, in_charge, phone, supported_processes,
  target_sort_kg, target_bale_count, max_capacity_kg, branch_id,
  created_at, updated_at
)
select code, name, coalesce(active, true), in_charge, phone, coalesce(supported_processes, '{}'),
       target_sort_kg, target_bale_count, max_capacity_kg, branch_id,
       created_at, updated_at
from public.warehouses
where code ~ '^KD-[0-9]+$'
on conflict (code) do update set
  name = excluded.name,
  active = excluded.active,
  in_charge = excluded.in_charge,
  phone = excluded.phone,
  supported_processes = excluded.supported_processes,
  target_sort_kg = excluded.target_sort_kg,
  target_bale_count = excluded.target_bale_count,
  max_capacity_kg = excluded.max_capacity_kg,
  branch_id = excluded.branch_id,
  updated_at = excluded.updated_at;

-- Existing documents still point at the old KD rows through warehouse_id.
-- Keep those rows as inactive FK anchors for historical integrity; all new
-- godown reads and writes use public.godowns, while stock warehouses use
-- active rows with a non-null type in public.warehouses.
update public.warehouses
set active = false, updated_at = now()
where code ~ '^KD-[0-9]+$';

comment on table public.godowns is 'Physical operating locations (KD). Separate from stock warehouses.';
comment on table public.warehouses is 'Stock warehouses. Inactive KD rows are legacy FK anchors only.';

commit;
