begin;

alter table public.production_inputs
  add column if not exists stock_category text;

update public.production_inputs pi
set stock_category = source.output_category
from lateral (
  select sl.output_category
  from public.stock_ledger sl
  where sl.ref_type = 'PI'
    and sl.ref_id = pi.id::text
    and sl.movement_type = 'PRODUCTION_INPUT_OUT'
    and sl.output_category in ('RM', 'FG')
  order by sl.id asc
  limit 1
) source
where pi.stock_category is null;

alter table public.production_inputs
  add constraint production_inputs_stock_category_check
  check (stock_category is null or stock_category in ('RM', 'FG'));

create table if not exists public.production_input_returns (
  id bigint generated by default as identity primary key,
  production_input_id bigint not null references public.production_inputs(id) on delete restrict,
  order_id bigint not null references public.production_orders(id) on delete restrict,
  date date not null,
  qty numeric not null check (qty > 0),
  unit_cost numeric not null default 0,
  total_cost numeric not null default 0,
  reason text not null,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  created_at timestamptz(6) not null default now(),
  created_by text,
  updated_at timestamptz(6),
  updated_by text
);

create index if not exists idx_production_input_returns_input
  on public.production_input_returns(production_input_id, status);
create index if not exists idx_production_input_returns_order
  on public.production_input_returns(order_id, status);

create index if not exists idx_stock_ledger_production_return_ref
  on public.stock_ledger(ref_type, ref_no, movement_type)
  where ref_type = 'PI-RETURN';

drop index if exists public.idx_stock_ledger_production_ref;
create index idx_stock_ledger_production_ref
  on public.stock_ledger(ref_type, ref_no)
  where ref_type in ('PI', 'PI-REV', 'PI-RETURN', 'PO2', 'PO2-REV');

drop index if exists public.idx_stock_ledger_production_ref_movement;
create index idx_stock_ledger_production_ref_movement
  on public.stock_ledger(ref_type, ref_no, movement_type)
  where ref_type in ('PI', 'PI-REV', 'PI-RETURN', 'PO2', 'PO2-REV');

commit;
